-- #######################################################################################
-- AUTOGENERATED HYPRLAND CONFIG.
-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hyprland.conf AND EDIT IT,
-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hyprland.org/Configuring/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

--###############
--## MONITORS ###
--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60",
    position = "0x0",
    scale = "auto",
    bitdepth = 10,
    cm = "hdr",
    sdrbrightness = 1.0,
    sdrsaturation = 0.98,
})

-- hl.monitor({
--     output = "HDMI-A-1",
--     mode = "3840x2160@60",
--     pos = "0x0",
--     scale = "auto",
--     bitdepth = 10,
--     color_management = "hdr",
--     sdr_brightness = 1.0,
--     sdr_saturation = 0.98
-- })

local terminal = "kitty"
local fileManager = "nautilus"
local web_browser = "google-chrome-stable"
local code = "code"
local menu = "wofi"

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

hl.env("MOZ_ENABLE_WAYLAND", "1")

hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("WLR_NO_HARDWARE_CURSORS", "1")

hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_STYLE_OVERRIDE", "kvantum")
hl.env("GTK_THEME", "Adwaita:dark")

-- TODO: manual review — malformed env on line 105: GDK_BACKEND,wayland,x11,*
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("CLUTTER_BACKEND", "wayland")

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.curve("overshot", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.1 } } })
hl.curve("smoothOut", { type = "bezier", points = { { 0.36, 0 }, { 0.66, -0.56 } } })
hl.curve("smoothIn", { type = "bezier", points = { { 0.25, 1 }, { 0.5, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.5, 0.5 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 2,
    bezier = "overshot",
    style = "popin",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 4,
    bezier = "smoothIn",
    style = "popin",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 4,
    bezier = "smoothIn",
    style = "popin",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 4,
    bezier = "default",
    style = "popin",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 10,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "fadeDim",
    enabled = true,
    speed = 10,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 3,
    bezier = "smoothIn",
    style = "slide",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 20,
    bezier = "linear",
})

hl.device({
    name = "asus-rog-gladius-ii",
    sensitivity = -0.7,
})

local mainMod = "SUPER" -- Sets "Windows" key as main modifier
local shiftMod = "SHIFT + SUPER" -- Sets "Windows + Shift" as secondary modifier

hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exit())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager .. " --new-window"))
hl.bind(mainMod .. " + Y", hl.dsp.exec_cmd(terminal .. " yazi"))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu .. " --show drun"))
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd(menu .. " --show run -I"))
hl.bind(mainMod .. " + P", hl.dsp.window.pin())
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(web_browser))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(terminal .. " lazydocker"))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal .. " --class trader /home/maxy/Tools/tradercli/trader.sh"))
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd(terminal .. " --class btop btop"))
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd(code))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("pidof hyprlock || hyprlock"))
hl.bind(mainMod .. " + Escape", hl.dsp.exec_cmd("rofi -show combi -combi-modes \"window, run, ssh\" -modes combi"))
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("wlogout --protocol layer-shell"))
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd("hyprpicker -f hex -a"))
hl.bind(mainMod .. " + U", hl.dsp.focus({ workspace = "11 && sleep 1 && hyprctl dispatch dpms off" }))
hl.bind(mainMod .. " + I", hl.dsp.exec_raw("hyprctl dispatch dpms on && sleep 4 && hyprlock"))
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m window --clipboard"))
hl.bind(shiftMod .. " + PRINT", hl.dsp.exec_cmd("hyprshot -m region --clipboard"))
hl.bind(mainMod .. " + H", hl.dsp.exec_cmd("hyprctl keyword monitor HDMI-A-1, 3840x2160@60, 0x0, auto, bitdepth, 10, cm, hdr, sdrbrightness, 1.0, sdrsaturation, 0.98"))
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("hyprctl keyword monitor HDMI-A-1, 3840x2160@60, 0x0, auto, bitdepth, 10, cm, hdr, sdrbrightness, 1.1, sdrsaturation, 0.98"))
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.exec_cmd("hyprctl keyword monitor HDMI-A-1, 3840x2160@60, 0x0, auto"))

hl.bind(mainMod .. " + SHIFT + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + right", hl.dsp.focus({ workspace = "+1" }))
hl.bind(mainMod .. " + left", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + Tab", hl.dsp.focus({ last = true }))
hl.bind("ALT + Tab", hl.dsp.window.cycle_next({ next = true }))
hl.bind("ALT + Tab", hl.dsp.window.bring_to_top())

hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind("Menu", hl.dsp.exec_cmd(menu .. " --show drun"), { locked = true, repeating = true })
hl.bind("XF86Calculator", hl.dsp.exec_cmd("gnome-calculator"), { locked = true, repeating = true })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ && /home/maxy/.config/mako/wp-vol.sh"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && /home/maxy/.config/mako/wp-vol.sh"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && /home/maxy/.config/mako/wp-vol.sh"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.window_rule({
    match = {
        class = "org.gnome.Calculator",
    },
    float = true,
    center = true,
    size = "350 600",
})

hl.window_rule({
    match = {
        class = "xdg-desktop-portal-gtk",
    },
    float = true,
    center = true,
    size = "monitor_w*0.5 monitor_h*0.5",
})

hl.window_rule({
    match = {
        class = "blueman-manager",
    },
    center = true,
    float = true,
    size = "monitor_w*0.5 monitor_h*0.5",
    border_size = 2,
})

hl.window_rule({
    match = {
        class = "com.saivert.pwvucontrol",
    },
    float = true,
    center = true,
    size = "monitor_w*0.5 monitor_h*0.5",
})

hl.window_rule({
    match = {
        class = "nm-connection-editor",
    },
    float = true,
    center = true,
    size = "monitor_w*0.5 monitor_h*0.5",
})

hl.window_rule({
    match = {
        class = "org.gnome.Nautilus",
    },
    float = true,
    center = true,
    size = "monitor_w*0.8 monitor_h*0.8",
})

hl.window_rule({
    match = {
        workspace = 1,
    },
    float = true,
    center = true,
    no_blur = true,
    no_dim = true,
    size = "monitor_w*0.6 monitor_h*0.6",
})

hl.window_rule({
    match = {
        class = "trader",
    },
    move = "5 40",
    size = "1530 1390",
})

hl.window_rule({
    match = {
        class = "btop",
    },
    size = "1530 1390",
})

hl.layer_rule({
    match = { namespace = "match:namespace hyprpicker" },
    -- TODO: manual review — unmapped layer rule: "no_anim on"
    -- TODO: manual review — unmapped layer rule: "dim_around 1"
})

hl.workspace_rule({
    workspace = "1",
    -- TODO: manual review — workspace field "float"
})

hl.workspace_rule({
    workspace = "2",
    gaps_in = 0,
    gaps_out = 0,
    -- rounding = 0,
    -- boarder = 0,
    decorate = 0,
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
    --##################
    --## MY PROGRAMS ###
    --##################
    -- See https://wiki.hyprland.org/Configuring/Keywords/
    -- Set programs that you use
    --################
    --## AUTOSTART ###
    --################
    -- Autostart necessary processes (like notifications daemons, status bars, etc.)
    -- Or execute your favorite apps at launch like this:
    -- exec-once = $terminal
    -- exec-once = nm-applet &
    -- exec-once = /home/maxy/.config/hypr/cascade-listener.sh &
    --############################
    --## ENVIRONMENT VARIABLES ###
    --############################
    -- See https://wiki.hyprland.org/Configuring/Environment-variables/
    -- Firefox
    -- Nvidia
    -- QT
    -- Toolkit Backend Variables
    -- XDG Specifications
    --####################
    --## LOOK AND FEEL ###
    --####################
    -- Refer to https://wiki.hyprland.org/Configuring/Variables/
    -- https://wiki.hyprland.org/Configuring/Variables/#general
    general = {
        gaps_in = 5,
        gaps_out = 6,
        border_size = 2,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        -- col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
        -- col.inactive_border = rgba(595959aa)
        col = {
            active_border = { colors = { "rgb(8aadf4)", "rgb(24273A)", "rgb(24273A)", "rgb(8aadf4)" }, angle = 45 },
            inactive_border = { colors = { "rgb(24273A)", "rgb(24273A)", "rgb(24273A)", "rgb(27273A)" }, angle = 45 },
        },
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#decoration
    decoration = {
        rounding = 10,
        rounding_power = 3,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 0.93,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 4,
            passes = 3,
            vibrancy = 0.1696,
        },
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#animations
    animations = {
        enabled = true,
    },
    -- Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
    -- "Smart gaps" / "No gaps when only"
    -- uncomment all if you wish to use that.
    -- workspace = w[tv1], gapsout:0, gapsin:0
    -- workspace = f[1], gapsout:0, gapsin:0
    -- windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
    -- windowrule = rounding 0, floating:0, onworkspace:w[tv1]
    -- windowrule = bordersize 0, floating:0, onworkspace:f[1]
    -- windowrule = rounding 0, floating:0, onworkspace:f[1]
    -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    -- dwindle {
    --     pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    --     preserve_split = true # You probably want this
    -- }
    -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    master = {
        new_status = "master",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#misc
    misc = {
        force_default_wallpaper = 0, --Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(
        -- mouse_move_enables_dpms=true
        key_press_enables_dpms = true,
    },
    --############
    --## INPUT ###
    --############
    -- https://wiki.hyprland.org/Configuring/Variables/#input
    input = {
        kb_layout = "us,ara",
        kb_variant = ",",
        kb_model = "",
        kb_options = "grp:win_space_toggle",
        kb_rules = "",
        numlock_by_default = true,
        follow_mouse = 1,
        sensitivity = -0.5, -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#gestures
    -- gestures {
    --     workspace_swipe = false
    -- }
    -- Example per-device config
    -- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
    -- experimental { 
    --     # Enable experimental features
    --     # See https://wiki.hyprland.org/Configuring/Experimental/
    --     # for more information about the features.
    --     enable = true
    --     # Enable HDR support
    --     hdr = true
    -- }
    --##################
    --## KEYBINDINGS ###
    --##################
    -- See https://wiki.hyprland.org/Configuring/Keywords/
    -- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
    -- bind = $mainMod, J, togglesplit, # dwindle
    -- Enable 4K 60Hz with 10-bit HDR and adjusted brightness/saturation
    -- Reset to standard 4K 60Hz (SDR)
    -- Move focus with mainMod + arrow keys
    -- Switch workspaces with mainMod + [0-9]
    -- workspace with mainMod + arrow keys
    -- Move active window to a workspace with mainMod + SHIFT + [0-9]
    -- Switch to the last workspace with mainMod + BACKSPACE
    -- Example special workspace (scratchpad)
    -- Scroll through existing workspaces with mainMod + scroll
    -- Move/resize windows with mainMod + LMB/RMB and dragging
    -- Apps Shortcuts
    -- Laptop multimedia keys for volume and LCD brightness
    -- bindel = $mainModd, EQUAL, exec, brightnessctl s 10%+
    -- bindel = $mainMod, MINUS, exec, brightnessctl s 10%-
    -- Laptop Keyboard brightness & backlight
    --bindel = ,XF86KbdBrightnessUp, exec, asusctl -n
    --bindel = ,XF86KbdBrightnessDown, exec, asusctl -p
    --bindel = ,XF86Launch3, exec, asusctl aura -n
    --bindel = ,XF86Launch2, exec, asusctl aura -p
    -- Laptop Performance mode
    --bindel = ,XF86Launch4, exec, asusctl profile -n
    -- Requires playerctl
    --#############################
    --## WINDOWS AND WORKSPACES ###
    --#############################
    -- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
    -- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
    -- Ignore maximize requests from apps. You'll probably like this.
    -- windowrule = match:class .*, suppressevent maximize
    -- Fix some dragging issues with XWayland
    -- windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
    -- Floating
    -- ######## Layer rules ########
    -- layerrule = noanim, gtk4-layer-shell
    -- # ######## Workspace rules ########
})

hl.on("hyprland.start", function()
    hl.exec_cmd("dunst")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("blueman-applet &")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme \"prefer-dark\"")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface text-scaling-factor 1.0")
end)

